  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.16.2
    mem_limit: 256m
    ports:
      - 8000:8000 
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/opentech/volumes/portainer_data:/data
